#!/bin/bash

# prepare_input
#   Input  : <xyz file> <charge> <multiplicity> <HEAD file> <TAIL file>
#   Output : The standard output generated by this script will be written to a
#            file named ${CALC_INP_FILENAME}. Each job will run as:
#
#            ${CALC_EXE} ${CALC_INP_FILENAME} > ${CALC_STDOUT_FILENAME}

input_xyz_file="$1"
chg="$2"
mult="$3"
HEAD_FN="$4"
TAIL_FN="$5"

chgmult="${chg} ${mult}"
SHEAD="$(cat "${HEAD_FN}" | sed 's/XXXXX/'"${chgmult}"'/g' | awk -v ORS='\\n' '{gsub(/\r$/,"")}1' | sed 's/\\n$//g')"
STAIL="$(cat "${TAIL_FN}"                                  | awk -v ORS='\\n' '{gsub(/\r$/,"")}1' | sed 's/\\n$//g')"
CHARCOMMENT='!'
echo -ne "${SHEAD}"
echo -n "${CHARCOMMENT}${CHARCOMMENT}${CHARCOMMENT} COMMENT FROM XYZ FILE : "
tail -n +2 "${input_xyz_file}"
echo -e "${STAIL}"
