#!/bin/bash

# prepare_input
#   Input  : <xyz file> <HEAD file> <TAIL file> <charge> <spin=2*S> <frozen>
#   Output : The standard output generated by this script will be written to a
#            file named ${CALC_INP_FILENAME}. Each job will run as:
#
#            ${CALC_EXE} ${CALC_INP_FILENAME} > ${CALC_STDOUT_FILENAME}

input_xyz_file="$1"
HEAD_FN="$2"
TAIL_FN="$3"
chg="$4"
spin="$5"
frozen="$6"

# parse dummy atoms specified by "ATOM : "
dummy=$(tail -n +3 "${input_xyz_file}" | grep " : " | sed 's/[[:space:]]*: .*$/1/g' | sort | uniq | tr '\n' ',' | sed 's/,$//g')
dummy=${dummy:+dummy,$dummy}

SHEAD="$(cat "${HEAD_FN}" | sed 's/XXXXXX/'"${chg}"'/g' | sed 's/SSSSSS/'"${spin}"'/g' | sed 's/ZZZZZZ/'"${frozen}"'/g' | sed 's/DDDummyDDD/'"${dummy}"'/g' | awk -v ORS='\\n' '{gsub(/\r$/,"")}1' | sed 's/\\n$//g')"
STAIL="$(cat "${TAIL_FN}" | sed 's/XXXXXX/'"${chg}"'/g' | sed 's/SSSSSS/'"${spin}"'/g' | sed 's/ZZZZZZ/'"${frozen}"'/g' | sed 's/DDDummyDDD/'"${dummy}"'/g' | awk -v ORS='\\n' '{gsub(/\r$/,"")}1' | sed 's/\\n$//g')"
CHARCOMMENT='!'
echo -e "${SHEAD}"
echo -n "${CHARCOMMENT}${CHARCOMMENT}${CHARCOMMENT} COMMENT FROM XYZ FILE : "
tail -n +2 "${input_xyz_file}" | sed 's@[[:space:]]*: @1 @g'
echo -e "${STAIL}"
